Repository vtex-apps/login, pull requests merged in 2019-01, with the labels that each got.

#91 Use ButtonWithIcon in favour of Button from styleguide
  CHANGELOG.md
  manifest.json
  package.json
  react/Login.js
  react/components/AccountOptions.js
  react/components/CodeConfirmation.js
  react/components/EmailAndPassword.js
  react/components/EmailVerification.js
  react/components/GoBackButton.js
  react/components/LoginComponent.js
  react/components/LoginOptions.js
  react/components/OAuth.js
  react/components/PasswordInput.js
  react/components/PasswordValidationContent.js
  react/components/RecoveryPassword.js
  react/propTypes.js
Labels: chore

#92 fix spacing on login
  CHANGELOG.md
  react/LoginContent.js
Labels: bug

#90 Bye pages.json! Welcome store-builder
  CHANGELOG.md
  manifest.json
  package.json
  pages/pages.json
  react/Login.js
  react/LoginContent.js
  react/components/AccountOptions.js
  react/components/LoginComponent.js
  react/package.json
  store/blocks.json
  store/interfaces.json
Labels: enhancement
